### ISSUE TITLE
Missing "await" in some cases when generating code

### ISSUE THREAD

**Issue by dlucredio** [dlucredio/js-distributor#23]
In the following example:

```
function soma(a, b) {
    console.log(`Adding ${a} + ${b}...`);
    const c = a + b;
    return c;
}

function main() {
    console.log(`Running main()...`);
    const value = soma(5, 6);
    console.log(`5 + 6 = ${value}`);
    return value;
}

```
with the following config.yml:"

```
codeGenerationParameters:
  mode: single                      # single | watch
  inputFolder: '../app'             # monolith folder (relative to config.yml)
  outputFolder: 'distributed'       # distributed folder (relative to config.yml)
  cleanOutput: true                 # delete output folder before?
  generateProjects: true            # generate new npm projects?
  generateDocker: false             # generate docker files for each server?
  ignore:                           # ignore the following folders
    - "node_modules"
    - "database_volume"
    - ".git"
rabbitParameters:
  url: localhost
  port: 5672
  numConnectionAttempts: 5
  timeBetweenAttempts: 10
servers:
  - id: alpha
    http:
      url: localhost
      port: 3000
    functions:
      - declarationPattern: 'main'
        method: http-get
  - id: beta
    http:
      url: localhost
      port: 3001
    functions:
      - declarationPattern: 'soma'
        method: http-post
```

The generated `start.js` for the alpha server is missing an await in the call to function `soma`:

```
import express from 'express';
import {
    main_localRef as main
} from "./main.js";
const app = express();
const port = 3000;
app.use(express.json());
app.get('/main', (requestParameter, responseParameter) => {
    const executionResult = main(); // <= We're missing an "await" here
    return responseParameter.json({
        executionResult
    });
});
app.listen(port, () => {
    console.log('Server running in port ' + port);
});
```
